### ISSUE TITLE
Error occurred when building "Sample-App-Src/Calculator"

### ISSUE THREAD

**Issue by BINGOGO123** [microsoft/testbase#24]
I have cloned this project and compeleted the Prerequisites mentioned in "Sample-App-Src/Calculator", 

> [.NET SDK](https://dotnet.microsoft.com/download)
> [Node.js](https://nodejs.org/en/)
> [WiX Toolset](https://github.com/wixtoolset/wix3/releases) After installation, add path of wix toolset (e.g, C:\Program Files (x86)\WiX Toolset v3.14\bin) to system variables

but when I run `build.ps1`, the following error occurred at `dotnet publish "./CalculatorCLI" -r win-x64 -c Release -o "./CalculatorCLI/drop"`.

```
PS C:\Users\t-haibinzang\Desktop\microsoft\testbase\Sample-App-Src\Calculator> .\build.ps1
用于 .NET 的 Microsoft (R) 生成引擎版本 17.2.0+41abc5629
版权所有(C) Microsoft Corporation。保留所有权利。       

  正在确定要还原的项目…
C:\Users\t-haibinzang\Desktop\microsoft\testbase\Sample-App-Src\Calculator\CalculatorCLI\CalculatorCLI.csproj : error NU1101: 找不到包 Flee。源 Microsoft Visual Studio Offline Packages 中不存在具有此 ID 
的包
  未能还原 C:\Users\t-haibinzang\Desktop\microsoft\testbase\Sample-App-Src\Calculator\CalculatorCLI\CalculatorCLI.csproj (用时 185 ms)。
```

**Comment by BINGOGO123** [comment]
This error was caused by the Nuget not kowning where to get package 'Flee'. I open the file `%appdata%/NuGet/NuGet.config`, and the contents of the file are as follows:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration />
```

I add the packageSources tag in the configuration tag, and then it works. The revised file reads as follows:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    </packageSources>
</configuration>
```

**Comment by BINGOGO123** [comment]
By the way, the version of node may need to be heigher than 16. When I run 'npm install' with node version 12.8.0, the following error occurred.

```
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> Calculator@0.1.0 postinstall C:\Users\t-haibinzang\Desktop\microsoft\testbase\Sample-App-Src\Calculator
> electron-builder install-app-deps

Error: Cannot find module 'fs/promises'
Require stack:
- C:\Users\t-haibinzang\Desktop\microsoft\testbase\Sample-App-Src\Calculator\node_modules\builder-util\out\fs.js
- C:\Users\t-haibinzang\Desktop\microsoft\testbase\Sample-App-Src\Calculator\node_modules\electron-builder\out\cli\cli.js
- C:\Users\t-haibinzang\Desktop\microsoft\testbase\Sample-App-Src\Calculator\node_modules\electron-builder\cli.js
    at Function.Module._load (internal/modules/cjs/loader.js:618:27)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (C:\Users\t-haibinzang\Desktop\microsoft\testbase\Sample-App-Src\Calculator\node_modules\builder-util\src\fs.ts:5:1)   
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (C:\Users\t-haibinzang\Desktop\microsoft\testbase\Sample-App-Src\Calculator\node_modules\builder-util\src\util.ts:25:1)    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Calculator@0.1.0 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Calculator@0.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

Then I upgraded the version to 16.0.0, and everything was right.

**Comment by yazeng** [comment]
Thanks for reporting this issue and thanks for providing the remediate!
We'll look into the two issues and get back to you.

Best Regards,
Yan
Test Base for Microsoft 365 Team
